name: Build Android Library

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11  # 推荐使用 JDK 17 兼容 AGP 7.0+

    - name: Setup Gradle cache
      uses: gradle/gradle-build-action@v2

    - name: Refresh Dependencies
      run: ./gradlew :corekit:dependencies --refresh-dependencies

    - name: Build AAR
      run: ./gradlew :corekit:assembleRelease

    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        name: corekit-aar
        path: corekit/build/outputs/aar/*.aar
